### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by 0plus1** [softwaretailoring/wheelnav#66]
Hi,

Using NPM + Webpack.

I can correctly require wheelnav (require('wheelnav'))
But cannot require or import that weird modified version of Raphael.
However, I load it (require or destructured import) it throws: Uncaught TypeError: Cannot read property 'on' of undefined

Is there any way to fix this?

Thanks

**Comment by softwaretailoring** [comment]
Hi @0plus1 

Unfortunately, I didn't use Webpack until this time.
However, I would like to help on this for you. Can you send me your current code base? And some information about how to use it would be appreciated.

**Comment by tbazin** [comment]
Reopening this since I was faced with the same issue:
Managed to circumvent it by slightly editing the sources at `raphael.js`. I changed the way the `eve` events library (included in `raphael.js`) is exported, and forced it to be exposed as an AMD plugin rather than as a module, on line 380:
```JavaScript
    // force export as AMD plugin rather than exporting as a module
    // COMMENTED THIS OUT
    // (typeof module != "undefined" && module.exports) ? (module.exports = eve) :
    (typeof define != "undefined" ? (define("eve", [], function() { return eve; })) : (glob.eve = eve));
    }
)(window || this);
```

After that,
```JavaScript
let Raphael = require('./my_edited_wheelnav/raphael');  // the edited version
import 'wheelnav';  // points to the npm package in node_modules
```
, works!

**Comment by softwaretailoring** [comment]
Hi @tbazin 

Thanks for sharing it! 👍
